### ISSUE TITLE
Mejora estilo BaseInput

### ISSUE THREAD

**Issue by horgarler** [ispp-2324-ocial/frontend#102]
Ponerle un tipo a BaseInput para que se pueda elegir el estilo entre el actual (que se puede llamar default) y el nuevo, destinado a las vistas relacionadas con el inicio de sesión y el registro (que se puede llamar auth, ya que es para las vistas de autenticación). Para ello se debe usar el estilo css que se deja al final de este comentario.

Añadir también un Component para los selectores (usados para elegir categorías en la creación y edición de eventos y en el registro de clientes) con un estilo que que encaje con este mismo estilo css nombrado con anterioridad.

.form input {
  outline: 0;
  background: #ffffff;
  width: 100%;
  border: 2px solid #3e80d7;
  border-radius: 15px;
  margin-bottom: 1vh;
  padding: 15px;
  box-sizing: border-box;
  font-size: 16px;
}

**Comment by fravilpae** [comment]
> Añadir también un Component para los selectores (usados para elegir categorías en la creación y edición de eventos y en el registro de clientes) con un estilo que que encaje con este mismo estilo css nombrado con anterioridad.

Esto no tiene sentido hacerlo en esta issue porque no tiene nada que ver con baseinput, sería otro componente distinto
