### ISSUE TITLE
Arreglar error de tipo en `src/pages/client/events.vue`

### ISSUE THREAD

**Issue by ferferga** [ispp-2324-ocial/frontend#110]
Tras la actualización de la API, ha habido algunos cambios en el modelo de datos, por lo que hay que refactorizar todo el sistema de fechas en dicha página.

@ispp-2324-ocial/fullstack No sé si esto es un cambio deseado o es un bug en backend.

**Comment by Jeszamgue** [comment]
El modelo se cambio porque antes solo tenía una fecha y ahora tiene 2, una de inicio y otra de fin, es un cambio deseado, cuando hagamos la vista funcional lo arreglaremos
