### ISSUE TITLE
FIX: Arreglar errores de lint y de tipos

### ISSUE THREAD

**Issue by carvarsou** [ispp-2324-ocial/frontend#136]
Al ejecutar `npm run check` existen errores relacionados con lint.

**Comment by ferferga** [comment]
Aumento prioridad a 4 puesto que es necesario tener checks que sean útiles para no mergear código de mala calidad erróneamente.

**Comment by ferferga** [comment]
La gran mayoría de errores se ha arreglado en #158 

El único que queda debe de resolverse cuando @ispp-2324-ocial/backend arregle https://github.com/ispp-2324-ocial/backend/issues/110
