### ISSUE TITLE
Mapa

### ISSUE THREAD

**Issue by ferferga** [ispp-2324-ocial/frontend#32]
Home Assistant usa OpenStreetMap y tiene marcadores personalizados: https://github.com/home-assistant/frontend/tree/dev/src/components/map

**Comment by AitorRD** [comment]
En la PR #49 no se puede subir a develop por:
- Un error en del lint de async/await (en la pr viene más detallado)
- UN error del sonarcloud de seguridad que ya he comentado la posible solución en la PR
@ferferga si puedes revisar lo que he propuesto para subirlo comentalo por aquí.
