### ISSUE TITLE
FEATURE: Filtrado de eventos

### ISSUE THREAD

**Issue by adrrf** [ispp-2324-ocial/frontend#54]
Se debe poder filtrar los eventos por:
- categoria
- distancia
- fecha y hora

**Comment by carvarsou** [comment]
Se necesita crear un componente Bar para seleccionar el radio en kilómetros (radius) mediante el cursor.

**Comment by Domi-ATLAS** [comment]
Tras empezar a realizar esta implementación, hemos acordado modificar el modelo de eventos para que este tenga ademas de una fecha y hora de inicio del evento, otra de finalizacion de este, para poder optimizar el filtrado

**Comment by Domi-ATLAS** [comment]
Esta seria esa rama para añadir la modificacion a backend: https://github.com/ispp-2324-ocial/backend/tree/feat/46-a%C3%B1adir-fecha-hora-inicio-final

**Comment by Domi-ATLAS** [comment]
Se ha añadido una primera version del filtrado, donde el filtrado por categoria estaria finalizado, a falta de comprobación, por distancia en proceso, a falta de poco, y el de tiempo, recien empezado y comentado por el excesivo numero de errores.

**Comment by carvarsou** [comment]
Esta issue se va a implementar tanto a backend como en frontend y, por tanto, se ha segmentado en la issue #108 de frontend y en la issue 76 de backend: https://github.com/ispp-2324-ocial/backend/issues/76
