### ISSUE TITLE
FEATURE: Búsqueda de eventos

### ISSUE THREAD

**Issue by adrrf** [ispp-2324-ocial/frontend#55]
Se debe poder hacer una búsqueda por eventos, los campos que se deben tener en cuenta:
- nombre del evento
- descripción del evento
- nombre del que crea el evento

**Comment by Ramguerom** [comment]
Necesitamos las issues 32 y 36 aceptadas y mergeadas a develop para poder avanzar en esta tarea @adrrf @ferferga

**Comment by Jeszamgue** [comment]
Mientras tanto, crearemos un buscador genérico

**Comment by ferferga** [comment]
Entre esta noche y mañana reviso todo

**Comment by AitorRD** [comment]
La issue #32 solo queda revisar algunos checks me pongo a ello

> Necesitamos las issues 32 y 36 aceptadas y mergeadas a develop para poder avanzar en esta tarea @adrrf @ferferga

**Comment by fravilpae** [comment]
@ferferga Es posible que para los iconos haga falta instalar iconify.vue en el main.ts o en algún archivo? Estamos teniendo dudas sobre cómo añadir un icono

**Comment by ferferga** [comment]
@fravilpae No, simplemente hay que escribir el componente precedido de I.

I-mdi-account


Para el icono de mdi-account
