### ISSUE TITLE
FEATURE: likes

### ISSUE THREAD

**Issue by adrrf** [ispp-2324-ocial/frontend#58]
Se deben implementar las opiniones y valoraciones sobre el cliente/evento

**Comment by AitorRD** [comment]
Se asigna @Ramguerom a esta issue para realizar pair programming y agilizar el desarrollo de la tarea

**Comment by AitorRD** [comment]
Se "congela" el prgreso de esa issue para realiozar otras con mayor prioridad debido al cambio de tags

**Comment by AitorRD** [comment]
Se ha cambiado la issue a likes ya que es la función que se acordó en la reunión como más prioritaria, tanto rating como opiniones se hará en una issue posterior.
