### ISSUE TITLE
FEATURE: Compartir Evento

### ISSUE THREAD

**Issue by paupenfer1** [ispp-2324-ocial/frontend#69]
Esta issue tiene como objetivo implementar la funcionalidad de compartir eventos en nuestra plataforma. La capacidad de compartir eventos permitirá a nuestros usuarios difundir información sobre eventos relevantes por los medios que deseen.

**Comment by ferferga** [comment]
@paupenfer1 Por concretarlo un poco más, creo que lo ideal sería tener un botón con el icono de compartir al que se le pase como prop el id del evento y al hacer click copie en el portapapeles (mostrando una notificación de que se ha copiado con éxito) la ruta que el ``router,resolve`` nos ha generado.

Igual para esto necesitamos tener la vista de evento completa, si no el router.resolve no va a saber bien a qué pagina nos estamos refiriendo.

**Comment by paupenfer1** [comment]
Todavía no está creada la vista de detalles del evento para usuarios, por lo que no puedo hacer mucho de momento. @AitorRD está en ello, cuando la termine podré desarrollarlo

**Comment by ferferga** [comment]
Esta es la API para integrar el botón con el menú compartir del sistema: https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API

Aquí tienes la documentación del composable de Vue para implementarlo de forma totalmente reactiva: https://vueuse.org/core/useShare/#useshare

**Comment by ferferga** [comment]
Se aumenta la prioridad por ser una característica no añadida en el anterior sprint
