### ISSUE TITLE
Crear componente `Button`

### ISSUE THREAD

**Issue by ferferga** [ispp-2324-ocial/frontend#9]
https://www.shadcn-vue.com/docs/components/button.html

Debe de admitir también botones que solo tengan en su interior los iconos generados por `unplugin-icons`. Más info en README.

**Comment by ferferga** [comment]
@AitorRD Esto se puede cerrar ya no?

**Comment by AitorRD** [comment]
> @AitorRD Esto se puede cerrar ya no?

Esta issue esta asignada a @Ramguerom yo lo que hice fue cerrarla y me dijo @Ramguerom que la reabriese para cambiar algo no se si el da el visto bueno ya.

**Comment by Ramguerom** [comment]
@ferferga @AitorRD esta issue ya esta hecha, lo único que se detecto un error en el componente a la hora de realizar las vistas. Este error fue arreglado en la issue correspondiente a las vistas. Ya que nos encontrábamos trabajando en ella, y esta issue estaba cerrada en ese momento.

**Comment by ferferga** [comment]
La cierto pues, muchas gracias a los dos por confirmar @Ramguerom @AitorRD
