### ISSUE TITLE
FEATURE: Login de Cliente Ubicacion

### ISSUE THREAD

**Issue by Ramguerom** [ispp-2324-ocial/frontend#95]
Crear una vista, que una vez creado el perfil de usuario, te lleve a un mapa donde seleccionar la ubicación en la que tendrán lugar los eventos referentes a ese cliente.

**Comment by Ramguerom** [comment]
Esta Issue es una continuación de la Issue #52. Actualmente se encuentra en revisión para ser mergeada a develop

**Comment by AitorRD** [comment]
En la rama perteneciente issue #81 (Feat/81 client event list) se ha añadido esta funcionalidad
